const chemFormData = {
  property: '',
  date: '',
  applicator_name: '',
  paddock: {
    identification: '',
    treatment_area: '',
    growth_stage: '',
    crop_situation: '',
    comment: '',
  },
  pest_details: {
    pest_type: '',
    growth_stage: '',
    density: '',
    comments: '',
  },
  chemical_details: {
    product: '',
    action_group: '',
    batch_no: '',
    rate: '',
    whp: '',
    whp_end_date: '',
  },
  weather: {
    start_time: '',
    start_temp: '',
    start_rel_humidity: '',
    start_wind_speed: '',
    start_direction: '',
    start_variability: '',
    end_time: '',
    end_temp: '',
    end_rel_humidity: '',
    end_wind_speed: '',
    end_direction: '',
    end_variability: '',
  },
  application_details: {
    nozzle_brand: '',
    nozzle_type: '',
    spray_quality: '',
    angle: '',
    size: '',
    pressure: '',
    water_rate: '',
    quantity_applied: '',
    water_source: '',
  },
  general_comment: '',
};

export default chemFormData;
